inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 80

