# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e22d02e9d39d94e6fe70ecbebd1773934306a62fb23dc04e8981d594dca7b4f2ba5b4bd08135f8c0b872dc684bca694529df520140d10b4607bcd5ae181adc46

test:
  secret_key_base: 04bfc2df9524811820c770140bd5e2443adef6192ce45355c8a22468702e92aa0437ed09dabdc76e03a094e557cfcd8a71f503216f6c83014e83f7206f9bda40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
